apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: carts-db
  name: carts-db
  namespace: sock-shop
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: carts-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
