apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: catalogue-db
  name: catalogue-db
  namespace: sock-shop
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: catalogue-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
