apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: null
    name: loadtest
  spec: {}
  status:
    phase: Active
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      name: load-test
    name: load-test
    namespace: loadtest
  spec:
    progressDeadlineSeconds: 2147483647
    replicas: 2
    revisionHistoryLimit: 2147483647
    selector:
      matchLabels:
        name: load-test
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: load-test
      spec:
        containers:
        - args:
          - -c
          - while true; do locust --host http://front-end.sock-shop.svc.cluster.local
            -f /config/locustfile.py --clients 5 --hatch-rate 5 --num-request 100
            --no-web; done
          command:
          - /bin/sh
          image: weaveworksdemos/load-test:0.1.1
          imagePullPolicy: IfNotPresent
          name: load-test
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          beta.kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
kind: List
metadata: {}
