apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: session-db
  name: session-db
  namespace: sock-shop
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: session-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
