apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: shipping
  name: shipping
  namespace: sock-shop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: shipping
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
