kubectl convert -f carts-db-dep.yaml > fixed/carts-db-dep.yaml
kubectl convert -f carts-db-svc.yaml > fixed/carts-db-svc.yaml
kubectl convert -f carts-dep.yaml > fixed/carts-dep.yaml
kubectl convert -f carts-svc.yml > fixed/carts-svc.yml
kubectl convert -f catalogue-db-dep.yaml > fixed/catalogue-db-dep.yaml
kubectl convert -f catalogue-db-svc.yaml > fixed/catalogue-db-svc.yaml
kubectl convert -f catalogue-dep.yaml > fixed/catalogue-dep.yaml
kubectl convert -f catalogue-svc.yaml > fixed/catalogue-svc.yaml
kubectl convert -f front-end-dep.yaml > fixed/front-end-dep.yaml
kubectl convert -f front-end-svc.yaml > fixed/front-end-svc.yaml
kubectl convert -f loadtest-dep.yaml > fixed/loadtest-dep.yaml
kubectl convert -f orders-db-dep.yaml > fixed/orders-db-dep.yaml
kubectl convert -f orders-db-svc.yaml > fixed/orders-db-svc.yaml
kubectl convert -f orders-dep.yaml > fixed/orders-dep.yaml
kubectl convert -f orders-svc.yaml > fixed/orders-svc.yaml
kubectl convert -f payment-dep.yaml > fixed/payment-dep.yaml
kubectl convert -f payment-svc.yaml > fixed/payment-svc.yaml
kubectl convert -f queue-master-dep.yaml > fixed/queue-master-dep.yaml
kubectl convert -f queue-master-svc.yaml > fixed/queue-master-svc.yaml
kubectl convert -f rabbitmq-dep.yaml > fixed/rabbitmq-dep.yaml
kubectl convert -f rabbitmq-svc.yaml > fixed/rabbitmq-svc.yaml
kubectl convert -f session-db-dep.yaml > fixed/session-db-dep.yaml
kubectl convert -f session-db-svc.yaml > fixed/session-db-svc.yaml
kubectl convert -f shipping-dep.yaml > fixed/shipping-dep.yaml
kubectl convert -f shipping-svc.yaml > fixed/shipping-svc.yaml
kubectl convert -f sock-shop-ns.yaml > fixed/sock-shop-ns.yaml
kubectl convert -f user-db-dep.yaml > fixed/user-db-dep.yaml
kubectl convert -f user-db-svc.yaml > fixed/user-db-svc.yaml
kubectl convert -f user-dep.yaml > fixed/user-dep.yaml
kubectl convert -f user-svc.yaml > fixed/user-svc.yaml
